### PR TITLE
Move Scrollspy to second ToC

### PR DESCRIPTION
**Pull request by jason-fox**
- update CSS to include grid for main.
- Add new `scrollspy.include` parameter (and remove scrollspy from `nav.toc`

This should be merged after #85 as it extends the grid css.

### CODE REVIEW

**Review by infotexture — CHANGES_REQUESTED** [review]
Looks like the changes here may have broken several of the `--nav-toc` options. 🧐 

I tried testing locally with the DITA-OT docs repo, and got errors for everything except `--nav-toc=collapsible`:

```shell
$ dita -i userguide.ditamap \
       -f html5-bootstrap \
       -o out/dita-bootstrap-test-pr-88-lg-partial \
       --nav-toc=list-group-partial
       
Error: Invalid value for property nav-toc: list-group-partial

$ dita -i userguide.ditamap \
       -f html5-bootstrap \
       -o out/dita-bootstrap-test-pr-88-npss \
       --nav-toc=nav-pill-scrollspy \
       --menubar-toc.include=yes

Error: Invalid value for property nav-toc: nav-pill-scrollspy
```

**Comment by jason-fox** [comment]
Could you retry c6a005f has merged some changes.

```console
dita -i userguide.ditamap \
       -f html5-bootstrap \
       -o out/dita-bootstrap-test-pr-88-lg-partial \
       --nav-toc=list-group-partial
```

should work.   ` nav-pill-scrollspy` and ` list-group-scrollspy` are no longer options. You'll need to use `scrollspy.toc` - it accepts `list-group`, `nav-pill`, `list` or `none` as valid arguments.

```console
dita -i userguide.ditamap \
       -f html5-bootstrap \
       -o out/dita-bootstrap-test-pr-88-lg-partial \
       --nav-toc=list-group-partial \
       --scrollspy.toc=list-group
```

You can see an example under `release-notes/index.html`

# Example

Screenshot 2023-06-06 at 13 37 42

**Comment by jason-fox** [comment]
Docs added 369aaa

**Review by infotexture — COMMENTED** [review]
Thanks for the changes here. I think we've got it cleaned up to the point where it now works as described.

One minor nit I just noticed is that link targets in the Scrollspy ToC are obscured by the sticky header. You can see this issue on the DITA-OT _Release Notes_ page if you test with those docs.

If you click any of the Scrollspy links, the target scrolls to the top, but the heading is hidden by the sticky navbar menu.

This doesn't happen in the Bootstrap docs, so we may just need to grab a bit more of their CSS, which uses [scroll-margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-top) to compensate for the height of the navbar menu.

**Review by infotexture — APPROVED** [review]
Found and fixed another edge case when scrolling to topic chunks.

Merging…

**Pull request merged**
