### PR TITLE
Add Bootstrap Extension documentation

### PR DESCRIPTION
**Pull request by jason-fox**
Basic documentation to link to the Bootstrap Extension plugin.

### CODE REVIEW

**Comment by jason-fox** [comment]
Once again, should the plugin be moved over to your GitHub to keep it all in the same place?

**Review by infotexture — COMMENTED** [review]
Looks good, thanks. 

> should the plugin be moved over to your GitHub to keep it all in the same place?

As with the others, happy to move this if you'd prefer them all in one place, but also fine if you ever want to keep something like this in your own namespace. I'll leave that to you to decide.

We could still link to it from the main `dita-bootstrap` repo. Either way, we'll need to update the docs references here, so I'll leave this open for the moment.

**Comment by jason-fox** [comment]
Let's move it then, since Bootstrap Extension is very tightly bound to Bootstrap, `infotexture/dita-bootstrap.extension` is the most logical place to host  an extension to infotexture/dita-bootstrap`.

**Comment by infotexture** [comment]
@jason-fox This should be good to go now. 

- Shall we merge this and package up the initial release of [dita-bootstrap.extension](https://github.com/infotexture/dita-bootstrap.extension) for the registry?
- Shall we tag that as plug-in version 1.0.0, or change the initial version to 5.3.3 to indicate the DITA Bootstrap version it was designed for?
- Anything else you'd like to add or change before DITA-OT Day?

**Comment by jason-fox** [comment]
> Shall we merge this and package up the initial release of [dita-bootstrap.extension](https://github.com/infotexture/dita-bootstrap.extension) for the registry?

That sounds like a good plan. . :shipit: 

> Shall we tag that as plug-in version 1.0.0 or 5.3.3 to indicate the DITA Bootstrap version it was designed for or 5.3.0 to indicate the version of @slackero/bootstrap-extension it bundles?

I would opt for `5.3.0` - the extension is unlikely to be updated frequently, and appears to only be updated for Bootstrap Minor releases, not every build. Actually as more of the functions get bundled into Bootstrap proper (as has been the case in the past), then Bootstrap extension becomes less and less likely to be required.  The **dependency** of Extension would need to be DITA Bootstrap `5.3.4` since it relies on changes made since the last  DITA Bootstrap release.

> Anything else you'd like to add or change before DITA-OT Day?

DITA Bootstrap itself needs a new release, as does the Lunr plugin. Only bug fixes, but its important to get everything working on Windows.

**Comment by infotexture** [comment]
OK, packaged up the new releases for the Lunr, Sass, & Extensions and will now merge this, tag the 5.3.4 release here, and submit the whole lot to the registry.

**Pull request merged**
