### PR TITLE
Add breadcrumb Support

### PR DESCRIPTION
**Pull request by jason-fox**
Adds support for Bootstrap [Breadcrumb](https://getbootstrap.com/docs/5.0/components/breadcrumb/) components

- Update XSL
- Update Documentation
- Add parameter override - `args.breadcrumbs`

Working example [here](https://jason-fox.github.io/dita-ot-plugins/)

Screenshot 2022-01-01 at 18 44 01

### CODE REVIEW

**Comment by jason-fox** [comment]
The `args.breadcrumbs` parameter was removed from DITA-OT due to this issue - https://github.com/dita-ot/dita-ot/issues/2554

A non-bootstrap equivalent could be created by including a call to `gen-user-breadcrumb`

```diff
<xsl:template match="*" mode="addContentToHtmlBodyElement">
    <main xsl:use-attribute-sets="main">
      <article xsl:use-attribute-sets="article">
        <xsl:attribute name="aria-labelledby">
          <xsl:apply-templates select="*[contains(@class,' topic/title ')] |
                                       self::dita/*[1]/*[contains(@class,' topic/title ')]" mode="return-aria-label-id"/>
        </xsl:attribute>
        <xsl:apply-templates select="*[contains(@class, ' ditaot-d/ditaval-startprop ')]" mode="out-of-line"/>

+        <xsl:if test="$BREADCRUMBS = 'yes'">
+         <xsl:apply-templates select="$current-topicref" mode="gen-user-breadcrumb"/>
+        </xsl:if>
```

And creating a non-Bootstrap breadcrumb as shown:

```xsl
<xsl:template match="*" mode="gen-user-breadcrumb">

    <nav aria-label="breadcrumb">
      <small>
        <xsl:for-each select="ancestor::node()">
          <xsl:variable name="title">
            <xsl:apply-templates select="." mode="get-navtitle"/>
          </xsl:variable>
          <xsl:if test="normalize-space($title)">
              <xsl:choose>
                <xsl:when test="@href">
                  <a>
                    <xsl:attribute name="href" select="@href"/>
                    <xsl:value-of select="$title"/>
                  </a>
                </xsl:when>
                <xsl:otherwise>
                  <span>
                    <xsl:value-of select="$title"/>
                  </span>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:text> / <xsl:text>
          </xsl:if>
        </xsl:for-each>
        <xsl:variable name="title">
          <xsl:apply-templates select="." mode="get-navtitle"/>
        </xsl:variable>
        <xsl:if test="normalize-space($title)">
          <xsl:value-of select="$title"/>
        </xsl:if>
      </small>
    </nav>
  </xsl:template>
```

**Review by infotexture — COMMENTED** [review]
Since this was submitted before DITA-OT 3.7 landed, we may need to re-test to make sure it still works with 3.7, which includes [changes to the way parent links are processed](https://www.dita-ot.org/3.7/release-notes/#v3.7__3792), and this may affect bookmark generation in some cases.

**Review by infotexture — APPROVED** [review]
Tested with DITA-OT 3.6.1 & 3.7, seems to work fine in both cases.

When run on the sample document in this repo with

    dita --project=.github/dita-ot/html.xml --args.breadcrumbs=yes

the breadcrumbs include the title of the parent topic as _plain text_, **but this text is not linked**.

When run on the DITA-OT docs repo, the same code links all levels of the topic hierarchy in breadcrumbs as expected, so I assume this is a peculiarity of the sample document setup, rather than any flaw in the XSLT code.

**Comment by jason-fox** [comment]
This is as expected:

```xml
  <chapter>
    <topicmeta>
      <navtitle>Components</navtitle>
    </topicmeta>
    <topicref navtitle="Accordion" format="dita" type="topic" href="accordion.dita"/>
   ...
```

In this case the parent topic (the `<chapter>` has a `<title>` but no `href`. It is included in the breadcrumb for reference but can only be included as a `<span>`

**Comment by jason-fox** [comment]
If Components had a topic, it would be a link.

```xml
  <topicref navtitle="Components" format="dita" type="topic" href="components.dita">
    <topicref navtitle="Accordion" format="dita" type="topic" href="accordion.dita"/>
   ...
</topicref>
```

**Comment by infotexture** [comment]
Of course, thanks, didn't dawn on me that those top-level sections were only navtitles.
Should've checked the source. 🤦 

Makes sense, merging…

**Pull request merged**
