### PR TITLE
Add sections to scrollspy

### LINKED ISSUE #226: Create scrollspy TOC also for sections?
Not a bug, but a possible feature:

Currently the scrollspy TOC is only created for chunked topics, not sections. 

Would it be a useful feature to also include section titles in the scrollspy TOC, and would it be require a major redesign?

### PR DESCRIPTION
**Pull request by jason-fox**
- Update XSLT
- Update images from GIF to WEBP
- Update documentation.

Fixes  #226

Note that only `scrollspy.dita` and `carousel.dita` have been updated to include `<section id="...">`

### CODE REVIEW

**Review by infotexture — APPROVED** [review]
@jason-fox Thanks for the updates here.

I agree with https://github.com/infotexture/dita-bootstrap/issues/226#issuecomment-2552238024: makes sense to omit untitled sections, and any without IDs.

In testing, I noticed that the `.active` state in the scrollspy page ToC does not follow along in `--scrollspy-toc=list` mode when scrolling. It does in list-group and nav-pill modes, but that difference appears to be unrelated to the changes on this branch, so I'd be fine merging this as is.

**Comment by infotexture** [comment]
@jason-fox Our last release was long ago. 

I'd like to bump the version numbers and submit new versions of this and the other plug-ins to the registry soon. 

Let me know if there's anything else you'd like to adjust beforehand.

**Comment by jason-fox** [comment]
>  the `.active` state in the scrollspy page ToC does not follow along ...

I think this is a known bug in Bootstrap 5.1.2 onwards.

> I'd like to bump the version numbers and submit new versions of this and the other plug-ins to the registry soon.
> Let me know if there's anything else you'd like to adjust beforehand.

Sure, there is nothing obvious from my side.  However,  Bootstrap `5.3.4` may be landing soon - it would be good to include that if possible.

**Comment by infotexture** [comment]
> Bootstrap `5.3.4` may be landing soon

OK, that's good to know. I had wondered, but hadn't heard any news, so wasn't sure.
But after your comment, I checked their repo and found a [5.3.4 release branch](https://github.com/twbs/bootstrap/commits/xmr/release-534/), so probably worth waiting.

I'll merge this in the meantime, and when the new version lands upstream, we can package up 5.3.5 versions of these plug-ins to include Bootstrap 5.3.4, and perhaps a new Bootswatch version if they follow suit.

**Pull request merged**
