### PR TITLE
Pagination Support

### PR DESCRIPTION
**Pull request by jason-fox**
This PR adds in topic and ditamap driven support for the Bootstrap [pagination bar](https://getbootstrap.com/docs/5.1/components/pagination/)

- XSL updates
- String internationalization
- Documentation

Screenshot 2022-01-23 at 13 52 35

A pagination bar can also be automatically added to the bottom of each page via parameters

Screenshot 2022-01-23 at 13 52 41

### CODE REVIEW

**Review by infotexture — COMMENTED** [review]
@jason-fox Thanks for all your input here lately, sorry it’s taken me so long to catch up with your progress.

### How to best review these?

It looks like several of the recent PRs here build on one another, so the volume of changes in each PR is a bit overwhelming in some cases, and makes a focused review of the actual changes rather difficult.

I’ll start by merging the dependency changes in #24, as it looks like several of the other PRs build on the latest version. 

Apart from that, from what I’ve seen so far, it looks like it will be easier to review & test these one-by-one in the order they were submitted, as rebasing may reduce the number of changes shown in subsequent PRs.

Let me know if you have any suggestions for the best order to review these (apart from what I can deduce from commit dates and the Git graph).

I'll try to test each of them and plan to package them up into a 5.3.1 release soon.

### Regarding pagination

I appreciate all your contributions here, but the use case for some things like pagination isn’t (yet?) readily apparent to me.

I’d like to avoid adding support for all sorts of Bootstrap constructs just because we can.

Everything we add here increases complexity and will need to be maintained in the future as DITA-OT processing and Bootstrap evolve.

This PR doesn't seem to contain DITA examples. How do you see this being used in DITA projects?

**Comment by infotexture** [comment]
@jason-fox Looks like this also includes the strings files changes from #23, so I marked this one as “draft” and added the `rebase required` label, so we remember to rebase it once the changes from #23 are merged.

**Comment by jason-fox** [comment]
@infotexture - Leave this one in draft until the others are complete.

> but the use case for some things like pagination isn’t  readily apparent to me.

1. If you look at  this [README](https://github.com/FIWARE/iotagent-isoxml#readme) for example, there is a prominent list of additional resources displayed on the page.

| :books: [Documentation](https://fiware-iotagent-isoxml.readthedocs.io) | :whale: [Docker Hub](https://hub.docker.com/r/fiware/iotagent-isoxml/) | :dart: [Roadmap](https://github.com/FIWARE/iotagent-isoxml/blob/master/docs/roadmap.md) |
| ---------------------------------------------------------------------- | ---------------------------------------------------------------------- | --------------------------------------------------------------------------------------- |

The `README` uses markdown of course, but I'd like to be able to get the same effect  using the bootstrap pagination look-and-feel - that can be done by marking up an ordered list `<ol outputclass=""pagination">`inside the `<topic>`.

2. If you look at the [documentation](https://fiware-iotagent-isoxml.readthedocs.io/en/latest/installationguide.html) and scroll to the bottom of the page, you can see **Next** and **Previous** buttons.  The equivalent is generated by `--bootstrap.pagination=partial` - it is similar to rel-links but styled in a bootstrap manner.  `--bootstrap.pagination=full` shows the same but also lists all the siblings, not sure how useful that one is, but it is most similar to a pagination in classic usage. 

> This PR doesn't seem to contain DITA examples. 

`sample/pagination.dita` shows the two use-cases in action.

**Comment by jason-fox** [comment]
🤔  maybe the way to do this is to split this in PR two.  **Pagination** could just be the _format a list of links into pagination bar_ as described in use case 1. The _add **Next** and **Previous** buttons_ could be a separate plugin extension of DITA bootstrap, that way other esoteric options could be isolated from the main plugin.

**Comment by jason-fox** [comment]
Superceded by #28

**Pull request closed without merging**
