### PR TITLE
Add collapsing navigation option for ToC 

### PR DESCRIPTION
**Pull request by jason-fox**
Additional ToC option using lists within [collapsible](https://getbootstrap.com/docs/5.1/components/collapse) elements - this seems to be a common paradigm for larger document sets ( e.g. [DITA-OT](https://www.dita-ot.org/dev/), [AWS](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.cloudwatchlogs.html), [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers) ) -  [Bootstrap](https://getbootstrap.com/docs/5.1/getting-started/introduction/) itself uses it on the Bootstrap docs.

-  Updated available parameters
-  Updated XSL
-  Updated Documentation
-  Added new images to the carousel.

### Collapsible

There is no need for a separate `partial` flag because the full ToC can always be rendered and won't take up too much space. Only the active elements are opened by default.  Active highlighting is purely on root and leaf elements. Also renders if the sub-menu is present.

collapsible

### CODE REVIEW

**Comment by infotexture** [comment]
@jason-fox Thanks for submitting, this is one thing I've been meaning to explore ever since the Bootstrap project updated their docs nav to use this approach. 🙏

I think this would be a great addition to the plug-in, but I'd like to refine the indentation to better align child topics to their parent titles:

| This PR                                                                                                                                          | Bootstrap Docs                                                                                                                              |
| ------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------- |
| dita-bootstrap-collapsible-toc-alignment | bootstrap-collapsible-toc-alignment |

The Bootrap docs don't seem to have expandable lower levels, but the same principles could be applied there as for the top level:

- Topic titles of non-expandable children align with the text of their parent topics
- Chevrons of expandable children align with the text of their parent topics

Looks like reducing the space between chevrons and topic titles to what Bootsrap uses might get us pretty close to the desired result.

**Comment by jason-fox** [comment]
Fixed 7e49716

Screenshot 2022-04-16 at 12 46 05

**Comment by infotexture** [comment]
Alignment looks much better now, but the changes may have had an unintended side effect.

The light purple background color from the Bootstrap docs that appears on hover covers _only_ on the topic title **or** the chevron, depending on which element is moused over:

dita-bootstrap-toc-hover

In the original implementation in the Bootstrap docs, hovering either chevron or title applies the background color to both, so they appear as a single unit.

**Comment by jason-fox** [comment]
The problem is that unlike Bootstrap, I don't know in advance if I'm dealing with one or two buttons. The XSL needs to deal with both of these  use-cases:

### Bootstrap Style - expand button only

```xml
<chapter>
  <topicmeta>
    <navtitle>Layout</navtitle>
  </topicmeta>
  <topicref navtitle="Grid" format="dita" type="topic" href="grid.dita"/>
</chapter>
```

### Amazon Style  - expand button  and doc link

```xml
<topicref navtitle="Layout" format="dita" type="topic" href="layout.dita">
  <topicref navtitle="Grid" format="dita" type="topic" href="grid.dita"/>
</topicref>
```

The reason I have two mouse over highlights is because I (sometimes) have two hit areas. 
The only way to be consistent, is to consistently have two buttons on each expandible row.  In the Bootstrap case, both buttons do the same thing.

I think the best way around this is to remove the purple button highlight (the purple is based on Bootstrap brand purple anyway) and rely on `link-primary` to give some indication of clickability hovering over the titles.

**Comment by jason-fox** [comment]
Fixed a13b752

**Review by infotexture — APPROVED** [review]
Thanks for the explanation. Looks like a good solution.

**Pull request merged**
