### PR TITLE
Add Bootstrap Table Plugin

### PR DESCRIPTION
**Pull request by jason-fox**
_DITA Bootstrap tables_ is a [DITA Open Toolkit plug-in](https://www.dita-ot.org/plugins) that extends the [DITA Bootstrap](https://infotexture.github.io/dita-bootstrap/) HTML output with additional features from the [Bootstrap tables](https://bootstraptabless.com) library.

Requires https://github.com/infotexture/dita-bootstrap/pull/193 - Another dependent plugin that may be useful.

Working example: https://jason-fox.github.io/dita-bootstrap.tables/

As usual I can move this over to keep the plugins together.

### CODE REVIEW

**Review by infotexture — COMMENTED** [review]
I'm open to this idea, but we since we already have the [Tables](https://infotexture.github.io/dita-bootstrap/tables.html) topic, we should probably extend both with reciprocal references to clarify the relationship between the table support that's provided out of the box in **DITA Bootstrap**, and the additional features provided by the new plug-in.

**Comment by infotexture** [comment]
> As usual I can move this over to keep the plugins together.

Makes sense to keep them all together of course — but the more we add, the more I wonder whether my namespace still makes sense. 🤔 

The new one would be the 5th in the series, and 4 out of 5 are your creations, so it feels a bit awkward to create the impression they're somehow mine. Especially so given the fact that I've had less time for reviews lately, so it's beginning to feel like I'm holding you up.

Might be time to consider moving them to a dedicated organization.

That would mean a bit of extra refactoring (and we'd need to redirect to the new home), but in the long run it might be best.

_What do you think?_

**Comment by jason-fox** [comment]
>  Might be time to consider moving them to a dedicated organization.
>
>  That would mean a bit of extra refactoring (and we'd need to redirect to the new home), but in the long run it might be best.
>
> _What do you think?_

Of the 5 repositories, 4 of them are exceedingly small (tables is literally two files. documentation and a `README`), and only one of them `dita-bootstrap` is of significant size. You're not exactly stealing my thunder, and besides which the license and footer copyrights are set up correctly.

I think in the long run you are correct, but I would hold off and I wouldn't do the rename refactoring until Bootstrap 6 and make the decision then. The main requirement for me is to keep everything together.

I'll raise the move request, and you can do what you see fit.

**Comment by infotexture** [comment]
> I'll raise the move request, and you can do what you see fit.

@jason-fox Sorry I dropped the ball here. The transfer link expired before I noticed it. 😥 

If you re-send, I'll accept and we can update the references here to match.

I see https://bootstrap-table.com uses the singular form in the name, so let's use that consistently in the plug-in name/ID.

**Comment by jason-fox** [comment]
Resent

**Comment by infotexture** [comment]
Renamed the copy to [infotexture/dita-bootstrap.table](https://github.com/infotexture/dita-bootstrap.table) & fixed a few paths and titles there. 

Merging this now.

**Pull request merged**
