### PR TITLE
Fix #6 - add custom ToC options

### LINKED ISSUE #6: Make list-group presentation for ToC optional
The latest changes apply the [Bootstrap List Group](https://getbootstrap.com/docs/5.0/components/list-group/) component style to the table of contents and embeds the full ToC in each page.

This approach works fine for small doc sets like the plugin's own docs, but doesn't scale well to publications that contain a large number of topics, where partial ToCs and standard unordered list presentation provide a better overview of the top-level items, and the current topic's place within that hierarchy.

We might want to consider adding a parameter that allows users to choose whether they want the ToC styled as a list group, or as a standard unordered list (which they can then style with custom CSS).

Another option might be to apply list group style when [nav-toc](https://www.dita-ot.org/dev/parameters/parameters-html5.html#html5__nav-toc)=`full`, but default to standard ULs when set to `partial`.

### PR DESCRIPTION
**Pull request by jason-fox**
Makes listGroup presentation optional. The plug-in extends the standard  `--nav-toc` parameter to add styled list groups for the sidebar. Five styles now are supported:

-  `bootstrap-full`  -  Bootstrap styled full TOC (default)
-  `bootstrap-partial` -  Bootstrap styled partial TOC that shows the current topic
-  `full` - Unstyled full TOC  (same as HTML5 Plugin)
-  `partial` - Unstyled  partial TOC that shows the current topic (same as HTML5 Plugin)
-  `none` - no TOC

### CODE REVIEW

**Review by infotexture — COMMENTED** [review]
👍 Thanks for implementing this so quickly. 

The ability to revert to the default HTML5 presentation as suggested in #6 will make this more useful in publications that contain a large number of topics, as the Bootstrap list group styling as currently implemented has limitations with regard to nesting depth.

Whereas the first and second levels are distinguished with color in `bootstrap-full` mode, subsequent levels appear the same as the second level.

In `bootstrap-partial` mode, child topics appear with the default UL • bullet, rather than applying the list group styles. _(I'll add a few screenshots to illustrate)_

I'm not sure how to handle this w/r/t defaults. On the one hand, I see the appeal of showcasing list group styling, but if it breaks with more than 2–3 levels, we might want to default to the standard UL presentation that works everywhere, and mention list group styling as an option for small docsets.

**Comment by infotexture** [comment]
Here's what the various ToC options look like when publishing the [dita-ot/docs](https://github.com/dita-ot/docs):

### Bootstrap full list group: `--nav-toc=bootstrap-full`

dita-bootstrap-pr7-bootstrap-full

### Bootstrap partial list group: `--nav-toc=bootstrap-partial`

dita-bootstrap-pr7-bootstrap-partial

### HTML5 full: `--nav-toc=full`

dita-bootstrap-pr7-full

### HTML5 partial: `--nav-toc=partial`

dita-bootstrap-pr7-partial

**Comment by jason-fox** [comment]
> I'm not sure how to handle this w/r/t defaults. On the one hand, I see the appeal of showcasing list group styling, but if it breaks with more than 2–3 levels, we might want to default to the standard UL presentation that works everywhere, and mention list group styling as an option for small docsets.

Funnily enough the [Bootstrap Docs](https://getbootstrap.com/docs/5.0/getting-started/introduction/) don't use a **List Group** for their menu either. For now I'll just rename the overrides as shown:

-  ~`bootstrap-full` - Bootstrap styled~ full TOC~
-  ~`bootstrap-partial` - Partial TOC that shows the current topic~
-  `list-group-full` -   full TOC within a Bootstrap [List Group](https://getbootstrap.com/docs/5.0/components/list-group/)
-   `list-group-partial`  -  partial TOC that shows the current topic within a Bootstrap [List Group](https://getbootstrap.com/docs/5.0/components/list-group/)
-  `full` - Unstyled full TOC (same as HTML5 Plugin)  **default**
-  etc.

As an aside - the nav should be using an HTML5 `<aside>` element too  to match the `<main>` - I guess that should be updated in the HTML5 plugin too.

**Comment by jason-fox** [comment]
>  it breaks with more than 2–3 levels,

Could you supply a small ditamap example of this breaking?

**Comment by infotexture** [comment]
> Could you supply a small ditamap example of this breaking?

You'll see it if you generate output using the DITA-OT docs `userguide.ditamap` from the `/docsrc/` folder of any recent DITA-OT distribution package.

See visible bullets in screenshot above in https://github.com/infotexture/dita-bootstrap/pull/7#issuecomment-860229263 under **“Bootstrap partial list group: `--nav-toc=bootstrap-partial`”**

**Comment by infotexture** [comment]
> the nav should be using an HTML5 `<aside>` element to match the `<main>`

🤔 I'm not so sure about that. 

I'm no expert on this, but from my reading of the spec/docs, our use of `<nav>` here seems semantically correct.

Per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside):
> The `<aside>` HTML element represents a portion of a document whose content is only indirectly related to the document's main content.

Though asides are often represented in sidebars, I'd say not all sidebars are asides — especially in cases like this where more semantically specific options are available.

Again, [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav):
> The `<nav>` HTML element represents a section of a page whose purpose is to provide navigation links

and later in the [Usage notes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav#usage_notes):
> A document may have several `<nav>` elements, for example, one for site navigation and one for intra-page navigation.

So it seems our global navigation in the header and the ToC sidebar are both valid uses of the `<nav>` element.

**Comment by jason-fox** [comment]
With a few tweaks this one is now looking good to go. This is a screenshot of the current `list-group-partial`:

Screenshot 2021-06-16 at 23 47 49

List Groups are usually just a single level of `<div>` elements, so it can't do deep hierarchies expressively. Currently the `list-group` uses the **primary** colour for the first level and **secondary** colour for everything else.

**Review by infotexture — APPROVED** [review]
> With a few tweaks this one is now looking good to go.

Indeed, thanks!

With the new utility classes and CI changes, there's more going on here than just the new ToC options, but makes sense to merge this all in, and treat any further tweaks separately.

**Pull request merged**
